//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Google_Pie_Chart_Report_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPieChart
    {
        public int BlogId { get; set; }
        public string Name { get; set; }
        public string CategoryName { get; set; }
        public Nullable<int> PostCount { get; set; }
    }
}
